# Use Docker environment
sudo: false

# Setup build matrix
language: php
php:
  - 5.6
  - 7
  - 7.1

install:
  - travis_retry composer update --no-interaction --prefer-source --dev

script: composer test